FROM plugins/base:linux-amd64

LABEL maintainer="Dheeraj Khardwal <dheeraj@khardwal.com>" \
  org.label-schema.name="Drone Maven" \
  org.label-schema.vendor="Dheeraj Khardwal" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-maven /bin/
ENTRYPOINT [ "/bin/drone-maven" ]
